version: '3'
services:
  nodejs-app:
    image: ankitjagtap/northladder_assignment:nodejs6
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: ankitjagtap/northladder_assignment:mongodb
    networks:
      - mynetwork

  redis:
    image: ankitjagtap/northladder_assignment:redis
    networks:
      - mynetwork

networks:
  mynetwork:
